# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customextension.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 382)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 381, 361))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblType = QtWidgets.QLabel(self.widget)
        self.lblType.setObjectName("lblType")
        self.horizontalLayout.addWidget(self.lblType)
        self.lneExtension = QtWidgets.QLineEdit(self.widget)
        self.lneExtension.setObjectName("lneExtension")
        self.horizontalLayout.addWidget(self.lneExtension)
        self.btnToevoegen = QtWidgets.QToolButton(self.widget)
        self.btnToevoegen.setObjectName("btnToevoegen")
        self.horizontalLayout.addWidget(self.btnToevoegen)
        self.btnVerwijderen = QtWidgets.QToolButton(self.widget)
        self.btnVerwijderen.setObjectName("btnVerwijderen")
        self.horizontalLayout.addWidget(self.btnVerwijderen)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lstCustom = QtWidgets.QListWidget(self.widget)
        self.lstCustom.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lstCustom.setObjectName("lstCustom")
        self.verticalLayout.addWidget(self.lstCustom)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblType.setText(_translate("Dialog", "Bestandstype"))
        self.lneExtension.setToolTip(_translate("Dialog", "Voeg hier de extensie toe van het bestandstype"))
        self.btnToevoegen.setToolTip(_translate("Dialog", "Voeg bestandstype toe"))
        self.btnToevoegen.setText(_translate("Dialog", "+"))
        self.btnVerwijderen.setToolTip(_translate("Dialog", "Verwijder geselecteerde extensie"))
        self.btnVerwijderen.setText(_translate("Dialog", "-"))
        self.lstCustom.setToolTip(_translate("Dialog", "lijst met extensies"))
